[project]
name = "mher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium-robotics[mujoco-py]>=1.4.2",
    "matplotlib>=3.10.8",
    "mpi4py>=4.1.1",
    "torch>=2.9.1",
]
